/**
 * Copyright (c) 2019 Yodlee, Inc. All Rights Reserved.
 *
 * Licensed under the MIT License. See LICENSE file in the project root for license information.
 */
package com.yodlee.api.model.transaction.enums;

public enum MeerkatTxnSubType {
	OVERDRAFT_CHARGE(3),
	ONLINE_PURCHASE(10),
	TAX_PAYMENT(13),
	PAYMENT_BY_CHECK(14),
	ATM_CASH_WITHDRAWAL(22),
	SERVICE_CHARGE(31),
	RETURNED_CHECK_CHARGE(33),
	STOP_PAYMENT_CHARGE(39),
	CONVENIENCE_FEE(43),
	AUTO_LOAN(46),
	HOME_LOAN_MORTGAGE(47),
	RECURRING_SUBSCRIPTION_PAYMENT(54),
	INTEREST(78),
	PAYMENT(80),
	PURCHASE(81),
	REFUND(82),
	TRANSFER(83),
	FINANCE_CHARGE(88),
	OTHER_CHARGES_FEES(90),
	ANNUAL_FEE(91),
	DEPOSIT(92),
	DIRECT_DEPOSIT_SALARY(93),
	INVESTMENT_INCOME_CASH(94),
	SSA(95),
	REWARDS(96),
	TAX_REFUND(100),
	CREDIT_CARD_PAYMENT(101),
	INSURANCE_PAYMENT(102),
	UTILITIES_PAYMENT(103),
	CHILD_SUPPORT(104),
	LOAN(105),
	PERSONAL_LOAN(106),
	STUDENT_LOAN(107),
	REIMBURSEMENT(109),
	BALANCE_TRANSFER(110),
	OVERDRAFT_PROTECTION(112),
	CREDIT(114),
	NSF_FEES(115);

	private long id;

	private MeerkatTxnSubType(long id) {
		this.id = id;
	}

	public long getId() {
		return id;
	}
}
