/**
 * Copyright (c) 2019 Yodlee, Inc. All Rights Reserved.
 *
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */
/*
 * Yodlee Core APIs This file describes the Yodlee Platform APIs, using the swagger notation. You can use this swagger
 * file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can
 * generate a client SDK for Python, Java, javascript, PHP or other languages according to your development needs. For
 * more details about our APIs themselves, please refer to https://developer.yodlee.com/Yodlee_API/.
 *
 * OpenAPI spec version: 1.1.0 Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class manually.
 */
package com.yodlee.sdk.client;

import org.apache.commons.lang3.StringUtils;

public class Pair {

	private String name = "";

	private String value = "";

	public Pair(String name, String value) {
		setName(name);
		setValue(value);
	}

	private void setName(String name) {
		if (!isValidString(name))
			return;
		this.name = name;
	}

	private void setValue(String value) {
		if (!isValidString(value))
			return;
		this.value = value;
	}

	public String getName() {
		return this.name;
	}

	public String getValue() {
		return this.value;
	}

	private boolean isValidString(String arg) {
		return !StringUtils.isBlank(arg);
	}
}
